# Generated by Django 2.2.1 on 2019-05-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('time_listed', models.DateTimeField(auto_now_add=True)),
                ('expired_listing', models.DateTimeField()),
                ('pay', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
