# Generated by Django 2.2.1 on 2019-06-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_auto_20190519_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chores',
            old_name='expired_listing',
            new_name='expire_date',
        ),
    ]
