# Generated by Django 2.2.1 on 2019-06-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_auto_20190531_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='chores',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
