# Generated by Django 2.2.1 on 2019-06-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_remove_chores_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='chores',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
