# Generated by Django 2.2.1 on 2019-06-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0006_chores_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chores',
            name='image',
            field=models.ImageField(blank=True, upload_to='kidschores/media/images/'),
        ),
    ]
