# Generated by Django 2.2.1 on 2019-06-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0007_auto_20190604_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chores',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
