# Generated by Django 2.2.1 on 2019-06-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0008_auto_20190605_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='chores',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
